### ISSUE TITLE
在获取角色面板时出错

### ISSUE THREAD

**Issue by QSlotus** [Mar-7th/March7th#30]
在获取角色面板时出错
```
2-26 13:44:45 [WARNING] nonebot_plugin_srpanel | 绘图出错：'HealRatioBase'
02-26 13:44:45 [ERROR] nonebot_plugin_srpanel | 'HealRatioBase'
Traceback (most recent call last):
  File "<string>", line 23, in <module>
  File "/root/.cache/pypoetry/virtualenvs/march7th-aJXRjhPa-py3.10/lib/python3.10/site-packages/nonebot/__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/march7th-aJXRjhPa-py3.10/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 201, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/march7th-aJXRjhPa-py3.10/lib/python3.10/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/march7th-aJXRjhPa-py3.10/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/march7th-aJXRjhPa-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
  File "/root/.cache/pypoetry/virtualenvs/march7th-aJXRjhPa-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/march7th-aJXRjhPa-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 846, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/march7th-aJXRjhPa-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 821, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/march7th-aJXRjhPa-py3.10/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "/data/March7th/march7th/nonebot_plugin_srpanel/__init__.py", line 145, in _
    img = await get_srpanel_img(player_info, info, score)
  File "/data/March7th/march7th/nonebot_plugin_srpanel/get_img.py", line 495, in get_srpanel_img
    + score[cid].main[relic_type][relic_info.main_affix.type]
KeyError: 'HealRatioBase'
```

**Comment by QSlotus** [comment]
> 出错的 UID 是多少，先使用 `srsupdate` 命令更新一下看是否还报错呢

106422231,已经更新过了而且就只有罗刹面板获取不了

**Comment by mobyw** [comment]
Fixed in https://github.com/Mar-7th/March7th/commit/c673665854ee9ac9d7257756421b88d3191dc95b
