### ISSUE TITLE
[BUG] 角色攻略报错：no such file or directory, open './data/nonebot_plugin_srres/guide/Nwflower/character_overview/1306.png'

### ISSUE THREAD

**Issue by sgpublic** [Mar-7th/March7th#35]
目录结构：

```
madray@NAS:/mnt/core/app/nonebot-march7th$ tree -L 2 --dirsfirst -a
.
├── app # 这个是把项目 clone 下来的目录
│   ├── accounts
│   ├── cache
│   ├── config
│   ├── data
│   ├── .devcontainer
│   ├── .git
│   ├── .github
│   ├── .idea
│   ├── march7th
│   ├── .env
│   ├── .env.prod
│   ├── .gitignore
│   ├── LICENSE
│   ├── poetry.lock
│   ├── .pre-commit-config.yaml
│   ├── .prettierrc
│   ├── pyproject.toml
│   └── README.md
├── .data
│   ├── accounts
│   ├── config
│   ├── data
│   └── .env.prod
└── start

14 directories, 11 files
```

部署方式：

```yaml
version: '3'
services:
  nonebot:
    image: mhmzx/poetry-runner:bookworm-20240211
    volumes:
      - /mnt/core/app/nonebot-march7th/app:/app
      - /mnt/core/app/nonebot-march7th/.data/accounts:/app/accounts
      - /mnt/core/app/nonebot-march7th/.data/config:/app/config
      - /mnt/core/app/nonebot-march7th/.data/data:/app/data
      - /mnt/core/app/nonebot-march7th/.data/.env.prod:/app/.env.prod
      - /mnt/core/app/nonebot-march7th/start:/start
      - /mnt/core/home/.ssh/docker:/home/poetry-runner/.ssh
      - /mnt/core/var/tmp/nonebot-march7th/poetry:/home/poetry-runner/.cache
      - /mnt/core/var/tmp/nonebot-march7th/app:/app/cache
    network_mode: host
    restart: always
```

/mnt/core/app/nonebot-march7th/start：

```shell
#!/bin/bash -e

mkdir -p ~/.cache/march7th
if [ ! -e "~/.cache/march7th/git.date" ]; then
        echo 0 > ~/.cache/march7th/git.date
fi

now=$(date +%Y%m%d)

if [ ! "$(cat ~/.cache/march7th/git.date)" == "$now" ]; then
        timeout 1m git pull
        poetry install
        echo "$now" > ~/.cache/march7th/git.date
fi

poetry run nb datastore upgrade
poetry run nb run
```

错误日志：

```
03-10 13:01:33 [SUCCESS] nonebot | OneBot V11 xxx | [message.group.normal]: Message -xxx from xxx@[群:xxx] '花火角色攻略'
03-10 13:01:33 [INFO] nonebot | Event will be handled by Matcher(type='message', module=march7th.nonebot_plugin_srwiki, lineno=55)
03-10 13:01:33 [INFO] nonebot | Matcher(type='message', module=march7th.nonebot_plugin_srwiki, lineno=55) running complete
03-10 13:01:33 [ERROR] nonebot | Running Matcher(type='message', module=march7th.nonebot_plugin_srwiki, lineno=55) failed.
Traceback (most recent call last):
  File "<string>", line 23, in <module>
  File "/home/poetry-runner/.cache/pypoetry/virtualenvs/march7th-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "/home/poetry-runner/.cache/pypoetry/virtualenvs/march7th-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/drivers/fastapi.py", line 201, in run
    uvicorn.run(
  File "/home/poetry-runner/.cache/pypoetry/virtualenvs/march7th-9TtSrW0h-py3.11/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/home/poetry-runner/.cache/pypoetry/virtualenvs/march7th-9TtSrW0h-py3.11/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/home/poetry-runner/.cache/pypoetry/virtualenvs/march7th-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/home/poetry-runner/.cache/pypoetry/virtualenvs/march7th-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/poetry-runner/.cache/pypoetry/virtualenvs/march7th-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 846, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/poetry-runner/.cache/pypoetry/virtualenvs/march7th-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 821, in simple_run
    await handler(
  File "/home/poetry-runner/.cache/pypoetry/virtualenvs/march7th-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/dependencies/__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/app/march7th/nonebot_plugin_srwiki/__init__.py", line 97, in _
    await msg_builder.finish(at_sender=True)
  File "/home/poetry-runner/.cache/pypoetry/virtualenvs/march7th-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot_plugin_saa/abstract_factories.py", line 324, in finish
    await self.send(at_sender=at_sender, reply=reply, **kwargs)
  File "/home/poetry-runner/.cache/pypoetry/virtualenvs/march7th-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot_plugin_saa/abstract_factories.py", line 302, in send
    return await self._do_send(bot, target, event, at_sender, reply)
  File "/home/poetry-runner/.cache/pypoetry/virtualenvs/march7th-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot_plugin_saa/abstract_factories.py", line 366, in _do_send
    return await sender(bot, self, target, event, at_sender, reply)
  File "/home/poetry-runner/.cache/pypoetry/virtualenvs/march7th-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot_plugin_saa/adapters/onebot_v11.py", line 200, in send
    res_dict = await bot.send_msg(message=message_to_send, **target.arg_dict(bot))
  File "/home/poetry-runner/.cache/pypoetry/virtualenvs/march7th-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/internal/adapter/bot.py", line 123, in call_api
    raise exception
  File "/home/poetry-runner/.cache/pypoetry/virtualenvs/march7th-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/internal/adapter/bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/home/poetry-runner/.cache/pypoetry/virtualenvs/march7th-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 144, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "/home/poetry-runner/.cache/pypoetry/virtualenvs/march7th-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/adapters/onebot/v11/utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message="Error: ENOENT: no such file or directory, open '/app/data/nonebot_plugin_srres/guide/Nwflower/character_overview/1306.png'", wording="Error: ENOENT: no such file or directory, open '/app/data/nonebot_plugin_srres/guide/Nwflower/character_overview/1306.png'", echo='1')
```

很奇怪的问题，我进 docker 看这个文件是能看到的，手动跑命令也能打开。

```
madray@NAS:/mnt/core/app/nonebot-march7th$ docker exec -it nonebot-march7th-nonebot-1 bash
root@NAS:/app# python3 
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> open('/app/data/nonebot_plugin_srres/guide/Nwflower/character_overview/1306.png')
<_io.TextIOWrapper name='/app/data/nonebot_plugin_srres/guide/Nwflower/character_overview/1306.png' mode='r' encoding='utf-8'>
```

**Comment by sgpublic** [comment]
> 使用的是哪个协议实现，以及对应的版本是什么

这还跟协议有关？我用的 LiteLoaderQQNT+[LLOneBot](https://github.com/LLOneBot/LLOneBot)，其他bot返图片貌似都是正常的，也用的同样的docker部署模式

**Comment by mobyw** [comment]
用的是哪个版本的 LLOneBot 呢

**Comment by sgpublic** [comment]
> 用的是哪个版本的 LLOneBot 呢

提交 issue 的时候用的是 v3.11.2，我现在更新到目前最新版 v3.11.10 还是有这个问题

**Comment by mobyw** [comment]
最新版版本号是 3.13.10，文件相关修复在  3.13.8

**Comment by sgpublic** [comment]
> 最新版版本号是 3.13.10，文件相关修复在 3.13.8

啊看错了抱歉，更新之后就是 v3.13.10，问题依旧

**Comment by mobyw** [comment]
LLOneBot 配置启用调试信息输出，复制一下报错时对应的调试日志

**Comment by sgpublic** [comment]
> LLOneBot 配置启用调试信息输出，复制一下报错时对应的调试日志

确实，看来不是容器内看不到文件，而是容器内看到的路径与外部不一致导致的，我连接方式用的反向ws，链接写的127.0.0.1，我还没看代码，也许是 March7th 当成本地直连了所以返了绝对路径。

```
2024/3/11 18:19:05 三月七(xxx): ws 消息上报 ws://127.0.0.1:23037/onebot/v11/ws/ {"self_id":xxx,"user_id":xxx,"time":1710152345,"message_id":-2147483336,"real_id":-2147483336,"message_type":"group","sender":{"user_id":xxx,"nickname":"忆丶距","card":"","role":"owner"},"raw_message":"花火角色攻略","font":14,"sub_type":"normal","message":[{"data":{"text":"花火角色攻略"},"type":"text"}],"message_format":"array","post_type":"message","group_id":xxx} 

2024/3/11 18:19:05 三月七(xxx): 收到反向Websocket消息 {"action":"send_msg","params":{"message":[{"type":"at","data":{"qq":"xxx"}},{"type":"image","data":{"file":"file:///app/data/nonebot_plugin_srres/guide/OriginMirror/character_overview/1306.png","type":null,"cache":"true","proxy":"true","timeout":null}}],"message_type":"group","group_id":xxx},"echo":"10"} 

2024/3/11 18:19:05 三月七(xxx): media path /home/madray/.config/QQ/nt_qq_e97b5b246831e82cf96f4ce2e2d67123/nt_data/Pic/2024-03/Ori/00def00e.png 

2024/3/11 18:19:05 三月七(xxx): 发生错误 {"errno":-2,"syscall":"open","code":"ENOENT","path":"/app/data/nonebot_plugin_srres/guide/OriginMirror/character_overview/1306.png"} 

2024/3/11 18:19:05 三月七(xxx): ws 消息上报 ws://127.0.0.1:23037/onebot/v11/ws/ {"status":"failed","retcode":1200,"data":null,"message":"Error: ENOENT: no such file or directory, open '/app/data/nonebot_plugin_srres/guide/OriginMirror/character_overview/1306.png'","wording":"Error: ENOENT: no such file or directory, open **'/app/data/nonebot_plugin_srres/guide/OriginMirror/character_overview/1306.png'","echo":"10"}
```

**Comment by mobyw** [comment]
攻略图片已修改为通过文件内容发送
