### ISSUE TITLE
在开始运行时报错无法运行

### ISSUE THREAD

**Issue by Dingtaiqi** [Mar-7th/March7th#59]
具体如下 
![image](https://github.com/user-attachments/assets/15910867-0f51-4c70-8a6f-f497bcd11379)
`08-06 07:13:06 [SUCCESS] nonebot | NoneBot is initializing...
08-06 07:13:06 [INFO] nonebot | Current Env: prod
Traceback (most recent call last):
  File "<string>", line 19, in <module>
  File "/mnt/7/.venv/lib/python3.11/site-packages/nonebot/internal/driver/abstract.py", line 91, in register_adapter
    self._adapters[name] = adapter(self, **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/7/.venv/lib/python3.11/site-packages/nonebot/adapters/red/adapter.py", line 46, in __init__
    self.setup()
  File "/mnt/7/.venv/lib/python3.11/site-packages/nonebot/adapters/red/adapter.py", line 57, in setup
    raise RuntimeError(
RuntimeError: Current driver ~fastapi doesn't support forward connections!RedProtocol Adapter need a ForwardDriver to work.
`

**Comment by mobyw** [comment]
可参考 README 中 Bot 配置部分进行配置
