### ISSUE TITLE
windows server 环境报错编码错误

### ISSUE THREAD

**Issue by xxtg666** [Mar-7th/March7th#6]
```
(march7th-py3.10) C:\Users\Administrator\Desktop\March7th>nb datastore upgrade
05-07 18:52:56 [SUCCESS] nonebot | NoneBot is initializing...
Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot\__init__.py", line 275, in init
    config = Config(
  File "pydantic\env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic\env_settings.py", line 75, in pydantic.env_settings.BaseSettings._build_values
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot\config.py", line 41, in __call__
    env_file_vars = self._read_env_files(settings.__config__.case_sensitive)
  File "pydantic\env_settings.py", line 225, in pydantic.env_settings.EnvSettingsSource._read_env_files
  File "pydantic\env_settings.py", line 330, in pydantic.env_settings.read_env_file
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\dotenv\main.py", line 382, in dotenv_values
    ).dict()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\dotenv\main.py", line 75, in dict
    self._dict = OrderedDict(resolve_variables(raw_values, override=self.override))
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\dotenv\main.py", line 233, in resolve_variables
    for (name, value) in values:
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\dotenv\main.py", line 83, in parse
    for mapping in with_warn_for_invalid_lines(parse_stream(stream)):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\dotenv\main.py", line 25, in with_warn_for_invalid_lines
    for mapping in mappings:
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\dotenv\parser.py", line 173, in parse_stream
    reader = Reader(stream)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\dotenv\parser.py", line 64, in __init__
    self.string = stream.read()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 293: invalid continuation byte
```
不知道是什么问题，这个服务器上也运行的别的nonebot是正常的，就这个报错……？

**Comment by xxtg666** [comment]
服务器配置的问题……解决了
